title: "juan's blog"
email: 24juanb@berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
  some cool problems I work on when I'm bored
baseurl: "/math-notes" # Set this to the repository name if your site is hosted under a subpath (for GitHub Pages)
url: "https://24juanb.github.io" # Your GitHub Pages base URL
twitter_username: jbg05
github_username: 24juanb

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Add this line to control post URLs
permalink: /:year/:month/:day/:title.html
